In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr1 = [1,2,3,4,5]
arr2 = [6,7,8,9,10]
arr3 = [2,3,4,5,6]

In [8]:
arr = np.array([arr1,arr2,arr3])

In [9]:
arr.shape

(3, 5)

In [11]:
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10,  2,  3],
       [ 4,  5,  6]])

In [12]:
arr.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 2,  3,  4,  5,  6]])

In [13]:
arr[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [14]:
arr[0:2, 3:]

array([[ 4,  5],
       [ 9, 10]])

In [15]:
arr[1:,0:2]

array([[6, 7],
       [2, 3]])

In [16]:
# Slicing and chosing the requird part of matrix
arr[1:2,1:4]

array([[7, 8, 9]])

In [24]:
# To chose the (from, to, points)
arr2 = np.linspace(1,10 ,50, dtype= int)
arr2

array([ 1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,
        4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  7,
        7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9, 10])

In [30]:
# To take create array (from , to , step)
arr5 = np.arange(0,10)
arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
#To change the shape of
arr5.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [35]:
# We use copy for not change in real Main array
arr6 = arr5.copy()
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
arr6[3:] = 200
arr6

array([  0,   1,   2, 200, 200, 200, 200, 200, 200, 200])

In [39]:
arr6[:4] = 100
arr6

array([100, 100, 100, 100, 200, 200, 200, 200, 200, 200])

In [44]:
# Changin values from that index
array = np.arange(1,15).reshape(7,2)
array[3:,:] = 200
array

array([[  1,   2],
       [  3,   4],
       [  5,   6],
       [200, 200],
       [200, 200],
       [200, 200],
       [200, 200]])

In [52]:
# To perform the conditional
array<20
array*2
array+20
array-5
array/2
array // 2
array%2

array([[1, 0],
       [1, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [56]:
# Gives element which is follows condition
array[array>199]
array[array<20]


array([1, 2, 3, 4, 5, 6])

In [57]:
array1 = np.arange(1,15).reshape(7,2)
array2 = np.arange(1,15).reshape(7,2)


In [61]:
# Multiply of 2 arrays
mul_array = array1 * array2
mul_array

array([[  1,   4],
       [  9,  16],
       [ 25,  36],
       [ 49,  64],
       [ 81, 100],
       [121, 144],
       [169, 196]])

In [62]:
mul_array*10

array([[  10,   40],
       [  90,  160],
       [ 250,  360],
       [ 490,  640],
       [ 810, 1000],
       [1210, 1440],
       [1690, 1960]])

In [63]:
mul_array.reshape(2,7)

array([[  1,   4,   9,  16,  25,  36,  49],
       [ 64,  81, 100, 121, 144, 169, 196]])

In [70]:
# To fill value by 1 default dtype is float

np.ones((1,10), dtype = int).reshape(5,2)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [72]:
# Random (row*col) from 0 to 1
np.random.rand(3,3)

array([[0.48315843, 0.09860441, 0.63260349],
       [0.34981621, 0.39766262, 0.73867146],
       [0.96911744, 0.71147781, 0.69093585]])

In [75]:
# Random (row*col) from 0 to 1
np.random.rand(4,4)

array([[0.77624615, 0.43438086, 0.54787379, 0.80610422],
       [0.8657954 , 0.67038073, 0.00360098, 0.71079047],
       [0.34907486, 0.16117583, 0.66912155, 0.10858425],
       [0.10102741, 0.89261324, 0.69982431, 0.89273912]])

In [78]:
# To take Random intezer value (from, to, step)
np.random.randint(1,10,8).reshape(4,2)

array([[4, 4],
       [4, 6],
       [8, 6],
       [6, 6]])

In [80]:
# To take Random Sample
np.random.random_sample((1,5)).reshape(5,1)

array([[0.45053115],
       [0.96298799],
       [0.99064019],
       [0.92102108],
       [0.0089253 ]])